version: '2'
services:
  web:
    image: nginx:1.10
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 8080:80
    links:
      - php
    depends_on:
      - php

  php:
    image: php:fpm
    volumes:
      - ./website:/var/www/website