version: '2'
services:
  web:
    image: nginx:1.12
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 8080:80
    links:
      - php
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./website:/var/www/website

  mariadb:
    image: mariadb:10.1
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      MYSQL_USER: php_user
      MYSQL_PASSWORD: sdrugntqqsciur
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: sdrugntqqsciur
    ports:
      - 3306:3306